# permissions for end users to edit filepickers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: azurefilepickercrd
    app.kubernetes.io/managed-by: kustomize
  name: filepicker-editor-role
rules:
- apiGroups:
  - azurefilepicker.example.com
  resources:
  - filepickers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azurefilepicker.example.com
  resources:
  - filepickers/status
  verbs:
  - get
